- hosts: all
  tasks:
    - name: chell
      shell: git remote -v
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: chell
      shell: git log origin/master..HEAD
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: shell
      shell: |
        for commit in $(git cherry master | cut -d " " -f2)
        do
            echo $commit
        done
      args:
        chdir: "{{ zuul.project.src_dir }}"
