- project:
    check:
      jobs:
        - ansible-galaxy-build-container-image
    pre-rlease:
      jobs:
        - release-ansible-python
    release:
      jobs:
        - release-ansible-python
