- job:
    name: runner-tox-base
    parent: tox
    required-projects:
      - name: github.com/ansible/ansible-runner
    vars:
      zuul_work_dir: ~/src/github.com/ansible/ansible-runner

- job:
    name: runner-tox-py27
    parent: runner-tox-base
    vars:
      tox_envlist: py27
    nodeset: centos-7-1vcpu

- job:
    name: runner-tox-py36
    parent: runner-tox-base
    vars:
      tox_envlist: py36
    nodeset: fedora-latest-1vcpu

- job:
    name: runner-tox-py37
    parent: runner-tox-base
    vars:
      tox_envlist: py37
    nodeset: fedora-latest-1vcpu

- project:
    check:
      jobs:
        - runner-tox-py27
        - runner-tox-py36
        - runner-tox-py37
