- job:
    name: galaxy-quick-start
    run: playbooks/run.yaml
    required-projects:
      - name: github.com/ansible/galaxy
      - name: github.com/ansible-network/releases
    nodeset: centos-8-1vcpu

- job:
    name: galaxy-quick-start-child
    dependencies:
      - name: galaxy-quick-start
    run: playbooks/child.yaml
    nodeset: centos-8-1vcpu

- project:
    check:
      jobs:
        - galaxy-quick-start
        - galaxy-quick-start-child
