- job:
    name: builder-test
    run: playbooks/run.yaml
    required-projects:
      - github.com/ansible/ansible-builder
    nodeset: ubuntu-bionic-4vcpu

- project:
    lgtm:
      jobs:
        - noop
    pre-rlease:
      jobs:
        - release-ansible-python
    release:
      jobs:
        - release-ansible-python
