- project:
    check:
      jobs:
        - ansible-tox-linters
    lgtm:
      jobs:
        - noop
    pre-rlease:
      jobs:
        - release-ansible-python
    release:
      jobs:
        - release-ansible-python
