---
- name: create dir
  file:
    path: "{{ download_artifact_directory }}"
    state: directory

- name: Download archive by type
  uri:
    url: "{{ artifact.url }}"
    dest: "{{ download_artifact_directory }}"
  loop: "{{ zuul.artifacts }}"
  loop_control:
    loop_var: artifact
  when: "'metadata' in artifact and 'type' in artifact.metadata and (artifact.metadata.type == download_artifact_type or ((download_artifact_type | type_debug) == 'list' and artifact.metadata.type in download_artifact_type))"
