---
- hosts: all
  tasks:
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: "-vv --notest"
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-builder'].src_dir }}"
